### ISSUE TITLE
Add labels?

### ISSUE THREAD

**Issue by ashish235** [dedalusj/cwmonitor#1]
Hi, 

Great tool mate. 
Is it possible to add labels of the containers as dimensions in the metrics, which can be useful in a scenario where container name changes after restart like in case of swarm. Using labels a single service can be plotted in graph easily. 

Regards, 
Ashish

**Comment by dedalusj** [comment]
Yeah the feature has merits. If I can think of a good syntax to specify the label to use from the command line I'll make it customisable otherwise I'll hardcode the label to use and document the behaviour.

Suggestions on syntax are welcome.

**Comment by ashish235** [comment]
I like the cadvisor type of labels, but there would be too many if all the labels are added. 

container_cpu_load_average_10s{container_label__base_version="amd64-0.4.10",container_label_com_docker_stack_namespace="kafka",container_label_com_docker_swarm_node_id="kwqs4zgd20dg0y7kphn0yddx3",container_label_com_docker_swarm_service_id="muja66z9ne51b9eyrxthf2bn9",container_label_com_docker_swarm_service_name="kafka_kafka1",container_label_com_docker_swarm_task_id="zbprqla0maz6fzw1pbwwlkmaj",container_label_com_docker_swarm_task_name="kafka_kafka1.1.zbprqla0maz6fzw1pbwwlkmaj",group="docker",id="/docker/153efd3cdbf0140a223d3bb6d9ba0a0b1b781846eaa79f64da0b8ff61bed21c0",image="hyperledger/fabric-kafka:latest@sha256:3b58cd0f26e7f4d8c49373d6b91e1e465a97321ce106da9c055ed452bb9d7184",instance="server1.internal.aws.com:8080",job="cadvisor",name="kafka_kafka1.1.zbprqla0maz6fzw1pbwwlkmaj"}

So that would be quite heavy to push so many labels, I think you can have a format like "CWMonitorLabel_CUSTOMKEYWORD=LABEL_VALUE"  so you consider the labels with this format. Just a suggestion. 


But I didn't find any docker API to get the labels with the docker stats API, so there might be separate calls needs to docker API to extract the complete data.

**Comment by dedalusj** [comment]
I added this in [v0.5.0](https://github.com/dedalusj/cwmonitor/tree/v0.5.0) please let me know if it does what you need.
